"use client";
import {createContext,useContext,useEffect,useState,useRef} from 'react';
import {createCase,project} from '@/lib/flowhome-v2/domain/domain.mjs';
import Navigation from './nav';
import {usePathname} from 'next/navigation';
import {DATASETS,createMarket,dispatchMarket,projectMarket,reserveMatch} from '@/lib/flowhome-v2/market.mjs';
import {MarketPanel} from './market-panel';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const validMarket=(p:any)=>p&&Number.isInteger(p.openingCashMinor)&&p.openingCashMinor>=0&&Array.isArray(p.cases)&&p.cases.length>0&&new Set(p.cases.map((c:any)=>c?.id)).size===p.cases.length&&p.cases.some((c:any)=>c.id===p.selectedCaseId)&&p.cases.every((c:any)=>c?.state?.schemaVersion===1&&c.state.config?.caseId===c.id&&Array.isArray(c.state.events)&&Array.isArray(c.state.tasks)&&Array.isArray(c.state.reservations)&&Array.isArray(c.state.assets)&&c.state.balances&&Object.values(c.state.balances).every(v=>typeof v==='number'&&Number.isFinite(v)));
const singleMarket=(state:any=createCase())=>({version:1,datasetId:'single',selectedCaseId:state.config.caseId,cases:[{id:state.config.caseId,name:'我的居住计划',district:'上海',intent:'move-in',state}],openingCashMinor:state.config.initialCashMinor});
import {Button} from '@/components/ui/button';
const Context=createContext<any>(null);
export {money,names} from './format';
import {names} from './format';
export function CaseProvider({children}:{children:React.ReactNode}){const pathname=usePathname();const[market,setMarket]=useState<any>(()=>singleMarket());const[dataset,setDataset]=useState('starter12');const state=market.cases.find((c:any)=>c.id===market.selectedCaseId).state;const marketView=projectMarket(market);const[ready,setReady]=useState(false);const[notice,setNotice]=useState<any>(null);const current=useRef<any>(null);
useEffect(()=>{let invalid=false;try{const raw=localStorage.getItem('flowhome-v3-market');if(raw){try{const p=JSON.parse(raw);if(!validMarket(p))throw new Error('INVALID_SAVED_MARKET');setMarket(p);if(DATASETS.some((d:any)=>d.id===p.datasetId))setDataset(p.datasetId);setReady(true);return}catch{invalid=true}}const old=localStorage.getItem('flowhome-v2.2-case');if(old){const next=singleMarket(JSON.parse(old));if(validMarket(next))setMarket(next);else invalid=true}}catch{invalid=true}if(invalid)setNotice({ok:false,text:'保存的新版演示无法读取，已恢复旧版案例或空白演示。'});setReady(true)},[]);
// Commit browser-local state before a document navigation can unmount the page.
function persist(next:any){try{localStorage.setItem('flowhome-v3-market',JSON.stringify(next));return true}catch{setNotice({ok:false,text:'此浏览器暂时无法保存演示进度，请允许网站存储后重试。'});return false}}

function act(role:string,type:string,payload:any={},actorId?:string){if(!ready)return {ok:false,error:{code:'RESTORING_CASE'}};const r=dispatchMarket(market,market.selectedCaseId,{id:'cmd-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),type,actor:{role,id:actorId??({resident:'resident-1',buyer:'buyer-1',ops:'ops-1',partner:'partner-alpha',governance:'reviewer-1'} as any)[role]},expectedVersion:state.aggregateVersion,payload});if(r.ok){if(!persist(r.market))return {ok:false,error:{code:'LOCAL_STORAGE_UNAVAILABLE'}};setMarket(r.market);setNotice({ok:true,text:'已记录 · '+r.result.eventId})}else setNotice({ok:false,text:'操作未执行：'+r.error.code});return r}
current.current={state,act};
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
register({name:'read_flowhome_case',description:'Read this browser-local simulated case status and resident account. No real service.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(!input||Object.keys(input).length)throw new Error('Empty object required');return (project as any)(current.current.state,'resident','resident-1')}});
register({name:'simulate_flowhome_command',description:'Execute a visible browser-local simulated service action. No real payment, dispatch or authentication.',inputSchema:{type:'object',properties:{role:{type:'string',enum:['resident','ops','partner','buyer','governance']},type:{type:'string'},payload:{type:'object'},expectedVersion:{type:'integer'}},required:['role','type','payload','expectedVersion'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!input||Object.keys(input).some(k=>!['role','type','payload','expectedVersion'].includes(k))||!['resident','ops','partner','buyer','governance'].includes(input.role)||typeof input.type!=='string'||!input.payload||typeof input.payload!=='object'||Array.isArray(input.payload))throw new Error('Invalid command');if(input.expectedVersion!==current.current.state.aggregateVersion)throw new Error('STALE_VERSION');const r=current.current.act(input.role,input.type,input.payload);return r.ok?{ok:true,result:r.result}:{ok:false,error:r.error}}});return()=>lifecycle.abort()},[]);
function reset(config={}){try{if(!ready)return;const next=singleMarket(createCase(config));if(!persist(next))return;setMarket(next);setNotice(null)}catch(e:any){setNotice({ok:false,text:e.message})}}
function bookMatch(demandId:string,supplyId:string){if(!ready)return;const r=reserveMatch(market,demandId,supplyId,'match-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));if(!r.ok){setNotice({ok:false,text:'未预约：'+r.error.code});return}const next={...r.market,selectedCaseId:supplyId};if(persist(next)){setMarket(next);setNotice({ok:true,text:'两位居民已通过预约关联。下一步到服务商接配送任务，再由接手者确认收货。'})}}
function selectCase(id:string){if(!ready)return;const next={...market,selectedCaseId:id};if(persist(next))setMarket(next)}
function loadDataset(){if(!ready)return;const next=createMarket(dataset);if(persist(next)){setMarket(next);setNotice({ok:true,text:'已载入模拟案例集；全部姓名、交易与服务均为虚构。'})}}
return <Context.Provider value={{state,market,marketView,selectCase,bookMatch,act,reset,view:(role:string,actorId?:string)=>project(state,role,actorId??({resident:'resident-1',buyer:'buyer-1',partner:'partner-alpha'} as any)[role]),notice}}><div className="v2"><Navigation/><main className="v2-work-main"><div className="v2-demo-bar"><span>模拟服务 · 跨界面共享 · 仅在此浏览器保存 · 角色切换不等于真实权限</span><div className="v3-toolbar"><Select value={dataset} onValueChange={setDataset} disabled={!ready}><SelectTrigger aria-label="模拟数据集"><SelectValue/></SelectTrigger><SelectContent>{DATASETS.map((d:any)=><SelectItem key={d.id} value={d.id}>{d.label}</SelectItem>)}</SelectContent></Select><Button size="sm" disabled={!ready} onClick={loadDataset}>使用模拟数据</Button><Button variant="ghost" size="sm" disabled={!ready} onClick={()=>reset()}>重置演示</Button></div></div><p className="v2-note">载入会替换本地演示；重置返回单人空白案例。市场案例与研究城市使用两套独立数据、费用假设。</p>{notice&&<div role="status" className={'v2-alert '+(notice.ok?'success':'error')}>{notice.text}</div>}<div inert={!ready}>{market.cases.length>1&&pathname!=='/lab'&&<MarketPanel market={market} summary={marketView} selectCase={selectCase} bookMatch={bookMatch}/>}<div key={market.selectedCaseId+':'+(market.matches?.length??0)}>{children}</div></div></main></div></Context.Provider>}

export const useCase=()=>useContext(Context);
export function Heading({eyebrow,title,description}:{eyebrow:string,title:string,description:string}){return <div className="v2-work-heading"><div><span className="v2-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div>}
export function Metric({label,value,note}:{label:string,value:any,note?:string}){return <div className="v2-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function Bill({label,value,total=false}:{label:string,value:any,total?:boolean}){return <div className={'v2-bill-row '+(total?'total':'')}><span>{label}</span><b>{value}</b></div>}
export function Status({status}:{status:string}){return <span className="v2-status">{names[status]??status}</span>}
