"use client";
import {useMemo} from 'react';
import {buildResearchView} from '@/lib/flowhome-v2/research-data.mjs';
import {useCase,Metric} from './context';
import {exportMarket} from './market-panel';
import {Button} from '@/components/ui/button';
export function ResearchData({city}:any){const {market,marketView}=useCase();const d=useMemo(()=>city?buildResearchView(city):null,[city]);return <><section className="v2-panel v3-data"><span className="v2-eyebrow">01 / DATASET REGISTRY</span><h2>先说明，我们正在研究什么数据。</h2><a className="v2-text-link" href="/downloads/market-research.md">多案例市场与研究台说明 ↗</a><div className="v3-market-columns"><div><h3>产品侧 · 多案例演示</h3><p>{market.datasetId} · 修订 {market.version}</p><div className="v2-value-grid"><Metric label="模拟服务案例" value={market.cases.length}/><Metric label="模拟产品事件" value={marketView.events.length}/></div><p className="v2-note">来自预置案例和你在本机的模拟操作。未接入真实用户、付款或服务商系统，也尚未导入城市引擎。</p><Button size="sm" variant="outline" onClick={()=>exportMarket(market)}>导出产品事件快照</Button></div><div><h3>城市侧 · 可复现合成世界</h3>{d?<><p className="v3-code">{d.dataset.datasetId}</p><div className="v2-value-grid"><Metric label="Mock 输入记录" value={d.dataset.counts.mockInputRows??'无法确认'}/><Metric label="真实记录" value="0"/></div><p>{d.dataset.counts.demandItems} 条需求 + {d.dataset.counts.initialAssets??'未知'} 件初始物品。{d.dataset.counts.weeklySnapshots} 周运行产生 {d.dataset.counts.events} 条事件。</p><p className="v2-note">输入、输出分开计数；需求条目不等于独立居民人数。种子 {city.config.seed}。{d.dataset.fixtureNote}</p></>:<p>正在核对当前运行的数据版本与数量…</p>}</div></div>{d&&<details><summary>查看字段、可见性与数据边界</summary><div className="v3-table-wrap"><table className="v2-table"><thead><tr><th>数据表</th><th>字段</th><th>算法何时可见</th></tr></thead><tbody>{d.dataset.fieldCatalog.map((r:any,i:number)=><tr key={i}><td>{r.table}</td><td className="v3-code">{r.fields.join(', ')}</td><td>{r.visibility}</td></tr>)}</tbody></table></div></details>}</section><section className="v2-panel v2-mt"><span className="v2-eyebrow">02 / COMPUTATION ENGINE</span><h2>研究规则，再检验规则的后果。</h2><p className="v3-code">引擎 {d?.dataset.engineVersion??'读取中'} · 算法 {d?.dataset.algorithmVersion??'读取中'}</p><div className="v3-engine-steps"><div><b>观察</b><p>当前公开库存、过去需求、服务容量与已承诺资金。</p></div><div><b>约束</b><p>先排除不符合预算、品质、期限与运力的方案。</p></div><div><b>排序</b><p>八周历史外推四周需求，比较保留物品的机会成本。</p></div><div><b>检验</b><p>同一随机世界里，比较有无预测的服务与财务结果。</p></div></div><p className="v2-note">当前是规则预测基线，没有训练过的 AI 模型。下方调参改变下一次实验；不能由一次较好结果推断真实市场优势。</p></section></>}
export function ResearchFlows({city,tick}:any){const d=useMemo(()=>buildResearchView(city),[city]);const week=d.weekly[tick];const max=Math.max(1,...d.weekly.map((w:any)=>w.newDemand));return <section className="v2-panel v2-mt"><span className="v2-eyebrow">03 / CITY IN MOTION</span><h2>一座城市，沿着时间流动。</h2><p>第 {tick+1} 周：{week.newDemand} 条新需求，{week.served} 次交付，{week.pickupPending} 件等待取件。</p><div className="v3-city-weeks" role="img" aria-label={`${d.weekly.length} 周新增需求柱图；蓝色为当前时间切片`}>{d.weekly.map((w:any)=><div key={w.tick} title={`第 ${w.tick+1} 周：${w.newDemand} 条需求`} style={{height:`${Math.max(3,w.newDemand/max*100)}%`,background:w.tick===tick?'#245cff':'#c2d0ed'}}/>)}</div><p className="v2-note">第 1 周 → 第 {d.weekly.length} 周。用下方“城市周数”滑杆回放。{d.geography.note}</p><div className="v3-table-wrap"><table className="v2-table"><thead><tr><th>品类（全运行累计）</th><th>到达需求</th><th>二手交付</th><th>新品交付</th><th>保障签约</th><th>回收完成</th></tr></thead><tbody>{d.categories.filter((c:any)=>c.arrivals||c.events).map((c:any)=><tr key={c.category}><td>{c.label}</td><td>{c.arrivals??'未确认'}</td><td>{c.usedHandovers}</td><td>{c.newHandovers}</td><td>{c.commitments}</td><td>{c.pickups}</td></tr>)}</tbody></table></div><p className="v2-note">上表覆盖完整运行；下方绩效指标采用排除前 12 周的比较窗口。签约、交付、回收是不同事件，不应相加当作人数；没有发生的流转不会画成已完成。</p></section>}
export function ResearchFeedback(){return <section className="v2-panel v2-mt"><span className="v2-eyebrow">04 / PRODUCT ↔ RESEARCH</span><h2>让每次使用，逐步改善下一次决策。</h2><div className="v3-engine-steps"><div><small>已实现 · 本地模拟</small><h3>事件快照</h3><p>案例、动作与账本关联，可导出检查。真实记录仍为 0。</p></div><div><small>待建设 · 数据接入</small><h3>质量与版本</h3><p>核对授权、缺失、时序和偏差；去标识化后冻结有来源的数据版本。</p></div><div><small>已实现 · 合成实验</small><h3>离线对照</h3><p>同种子、同责任比较策略。接入真实数据还需要时间切分与验证集。</p></div><div><small>待建设 · 发布治理</small><h3>人工审核</h3><p>同时查看服务覆盖、成本与群体差异，审核后才发布候选策略。</p></div></div><p className="v2-note">当前这条路径没有自动训练或自动上线。真实供需和履约数据能帮助校准需求、时长与服务容量，但其价值仍需对照验证。</p></section>}
